export const types = {
    FETCH_CHARACTERS_REQUEST: 'FETCH_CHARACTERS_REQUEST',
    FETCH_CHARACTERS_SUCCESS: 'FETCH_CHARACTERS_SUCCESS',
    FETCH_CHARACTERS_FAILURE: 'FETCH_CHARACTERS_FAILURE',
    FETCH_CAT_SUCCESS: 'FETCH_CAT_SUCCESS',
    FETCH_JOKE_SUCCESS: 'FETCH_JOKE_SUCCESS',
    FETCH_JSON_SUCCESS: "FETCH_JSON_SUCCESS",
    FETCH_TITAN_SUCCESS: 'FETCH_TITAN_SUCCESS'
}